import type { BdrRowDef, BdrSubType } from '../types/bdr';

export const BDR_ROWS: BdrRowDef[] = [
  { code: 'bdr_header', name: 'Статья БДР', isHeader: true },
  { code: 'revenue', name: 'Выручка', isSemiBold: true, isCalculated: true },
  { code: 'revenue_smr', name: 'Выручка от СМР всего (КС-2 с Заказчиком)', isCalculated: true },
  { code: 'execution_total', name: 'Выполнение всего (КС-2 внутренняя)', isCalculated: true },
  { code: 'contract_not_accepted', name: 'Всего работы по контракту выполненные, но не принятые заказчиком', isCalculated: true },
  { code: 'readiness_percent', name: 'Процент готовности с начала строительства', isPercent: true, isCalculated: true },
  { code: 'nzp_to_revenue', name: 'Отношение НЗП к Выручке', isPercent: true, isCalculated: true, noPlan: true },

  { code: 'cost_total', name: 'Себестоимость в т.ч.', isSemiBold: true, isCalculated: true, isCostParent: true },
  { code: 'cost_materials', name: 'Материальные расходы', isClickable: true, subType: 'materials', isCostChild: true },
  { code: 'cost_labor', name: 'ФОТ основных рабочих', isClickable: true, subType: 'labor', isCostChild: true },
  { code: 'cost_subcontract', name: 'Субподряд', isClickable: true, subType: 'subcontract', isCostChild: true },
  { code: 'cost_design', name: 'Проектные работы', isClickable: true, subType: 'design', isCostChild: true },
  { code: 'cost_rental', name: 'Аренда БК и подъемников', isClickable: true, subType: 'rental', isCostChild: true },
  { code: 'cost_overhead', name: 'Накладные расходы (косвенные) в т.ч. (ООЗ)', isClickable: true, isOverhead: true, isCalculated: true, isCostChild: true },

  { code: 'overhead_ratio', name: 'Коэф.накладных расходов', isPercent: true, isCalculated: true },
  { code: 'labor_cost_ratio', name: 'Доля ФОТ в себестоимости (Labor Cost Ratio)', isPercent: true, isCalculated: true },
  { code: 'marginal_profit', name: 'Маржинальная прибыль', isCalculated: true },
  { code: 'gross_margin', name: 'Маржинальная (Валовая) рентабельность (Gross Margin)', isPercent: true, isCalculated: true },
  { code: 'fixed_expenses', name: 'Постоянные коммерческие и управленческие расходы (в т.ч. Амортизация) (ОФЗ)', isPlanCalculated: true, isClickable: true, subType: 'fixed_expenses' },
  { code: 'operating_profit', name: 'Операционная прибыль', isCalculated: true },
  { code: 'operating_profit_pct', name: 'В % к общей прибыли', isPercent: true, isCalculated: true },
  { code: 'other_income_expense', name: 'Прочие доходы (расходы)' },
  { code: 'profit_before_tax', name: 'Прибыль (Убыток) до налогообложение', isCalculated: true },
  { code: 'income_tax', name: 'Налог на прибыль' },
  { code: 'net_profit', name: 'Чистая прибыль', isCalculated: true },
  { code: 'net_profit_margin', name: 'Рентабельность по чистой прибыли (Net Profit Margin)', isPercent: true, isCalculated: true },
  { code: 'dividends', name: 'Дивиденды и прочее распределение прибыли' },
];

export const BDR_OVERHEAD_ROWS: BdrRowDef[] = [
  { code: 'overhead_01', name: 'Оплата труда ИТР (в т.ч. Налоги с ФОТ)', isClickable: true, subType: 'overhead_labor' as const },
  { code: 'overhead_02', name: 'Водопотребление, водоотведение', isClickable: true, subType: 'overhead_02' as const },
  { code: 'overhead_03', name: 'Электроснабжение', isClickable: true, subType: 'overhead_03' as const },
  { code: 'overhead_04', name: 'Теплоснабжение', isClickable: true, subType: 'overhead_04' as const },
  { code: 'overhead_05', name: 'Охрана', isClickable: true, subType: 'overhead_05' as const },
  { code: 'overhead_06', name: 'Налоги и сборы', isClickable: true, subType: 'overhead_06' as const },
  { code: 'overhead_07', name: 'Комиссия по банковским гарантиям', isClickable: true, subType: 'overhead_07' as const },
  { code: 'overhead_08', name: 'Аренда строительного оборудования, механизмов, техники', isClickable: true, subType: 'overhead_08' as const },
  { code: 'overhead_09', name: 'Аренда ДГУ и котельных', isClickable: true, subType: 'overhead_09' as const },
  { code: 'overhead_10', name: 'Аренда автотранспорта', isClickable: true, subType: 'overhead_10' as const },
  { code: 'overhead_11', name: 'Аренда экскаваторов и погрузчиков', isClickable: true, subType: 'overhead_11' as const },
  { code: 'overhead_12', name: 'Аренда помещений, территорий, участков', isClickable: true, subType: 'overhead_12' as const },
  { code: 'overhead_13', name: 'Разр.и согл. Инстанции', isClickable: true, subType: 'overhead_13' as const },
  { code: 'overhead_14', name: 'Списание ОС', isClickable: true, subType: 'overhead_14' as const },
  { code: 'overhead_15', name: 'Списание (опалубка)', isClickable: true, subType: 'overhead_15' as const },
  { code: 'overhead_16', name: 'Списание (леса)', isClickable: true, subType: 'overhead_16' as const },
  { code: 'overhead_17', name: 'Услуги связи', isClickable: true, subType: 'overhead_17' as const },
  { code: 'overhead_18', name: 'Доп.выплаты сотрудникам', isClickable: true, subType: 'overhead_18' as const },
  { code: 'overhead_19', name: 'Штрафы', isClickable: true, subType: 'overhead_19' as const },
  { code: 'overhead_20', name: 'Проживание рабочих и линейщиков', isClickable: true, subType: 'overhead_20' as const },
  { code: 'overhead_21', name: 'Возмещение затрат заказчику', isClickable: true, subType: 'overhead_21' as const },
  { code: 'overhead_22', name: 'Страхование', isClickable: true, subType: 'overhead_22' as const },
  { code: 'overhead_23', name: 'Работы и затраты гарантийного периода', isClickable: true, subType: 'overhead_23' as const },
  { code: 'overhead_24', name: 'Прочие затраты и услуги', isClickable: true, subType: 'overhead_24' as const },
];

export const OVERHEAD_CODES = BDR_OVERHEAD_ROWS.map((r) => r.code);

export const COST_ROW_CODES = [
  'cost_materials',
  'cost_labor',
  'cost_subcontract',
  'cost_design',
  'cost_rental',
  'cost_overhead',
] as const;

export const BDR_SUB_TYPES: Record<BdrSubType, { title: string; rowCode: string }> = {
  materials: { title: 'Списание материалов', rowCode: 'cost_materials' },
  labor: { title: 'Оплата труда рабочих', rowCode: 'cost_labor' },
  subcontract: { title: 'Субподряд проекта', rowCode: 'cost_subcontract' },
  design: { title: 'Проектные работы по проекту', rowCode: 'cost_design' },
  rental: { title: 'Аренда БК и подъемников по проекту', rowCode: 'cost_rental' },
  fixed_expenses: { title: 'Постоянные коммерческие и управленческие расходы (ОФЗ)', rowCode: 'fixed_expenses' },
  overhead_labor: { title: 'Оплата труда ИТР (в т.ч. Налоги с ФОТ) по проекту', rowCode: 'overhead_01' },
  overhead_02: { title: 'Водопотребление, водоотведение', rowCode: 'overhead_02' },
  overhead_03: { title: 'Электроснабжение', rowCode: 'overhead_03' },
  overhead_04: { title: 'Теплоснабжение', rowCode: 'overhead_04' },
  overhead_05: { title: 'Охрана', rowCode: 'overhead_05' },
  overhead_06: { title: 'Налоги и сборы', rowCode: 'overhead_06' },
  overhead_07: { title: 'Комиссия по банковским гарантиям', rowCode: 'overhead_07' },
  overhead_08: { title: 'Аренда строительного оборудования, механизмов, техники', rowCode: 'overhead_08' },
  overhead_09: { title: 'Аренда ДГУ и котельных', rowCode: 'overhead_09' },
  overhead_10: { title: 'Аренда автотранспорта', rowCode: 'overhead_10' },
  overhead_11: { title: 'Аренда экскаваторов и погрузчиков', rowCode: 'overhead_11' },
  overhead_12: { title: 'Аренда помещений, территорий, участков', rowCode: 'overhead_12' },
  overhead_13: { title: 'Разр.и согл. Инстанции', rowCode: 'overhead_13' },
  overhead_14: { title: 'Списание ОС', rowCode: 'overhead_14' },
  overhead_15: { title: 'Списание (опалубка)', rowCode: 'overhead_15' },
  overhead_16: { title: 'Списание (леса)', rowCode: 'overhead_16' },
  overhead_17: { title: 'Услуги связи', rowCode: 'overhead_17' },
  overhead_18: { title: 'Доп.выплаты сотрудникам', rowCode: 'overhead_18' },
  overhead_19: { title: 'Штрафы', rowCode: 'overhead_19' },
  overhead_20: { title: 'Проживание рабочих и линейщиков', rowCode: 'overhead_20' },
  overhead_21: { title: 'Возмещение затрат заказчику', rowCode: 'overhead_21' },
  overhead_22: { title: 'Страхование', rowCode: 'overhead_22' },
  overhead_23: { title: 'Работы и затраты гарантийного периода', rowCode: 'overhead_23' },
  overhead_24: { title: 'Прочие затраты и услуги', rowCode: 'overhead_24' },
};
